version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FFMpegCore
    versions:
    - 3.3.0
    - 3.4.0
    - 4.0.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
